[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "GPL-3.0",
    "CC0-1.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
]
exceptions = [
    # Use exceptions for these as they only have a single user
    { allow = ["Zlib"], crate = "tinyvec" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
    { allow = ["OpenSSL"], crate = "ring" },
]

# From https://embarkstudios.github.io/cargo-deny/checks/cfg.html
[[licenses.clarify]]
crate = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
